apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-micro-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/denisgdevops/student-service.git # Replace with your GitLab repo URL
    targetRevision: feature/package-registry
    path: platform/helm # Path to your application's Kubernetes manifests
  destination:
    server: https://kubernetes.default.svc  # Minikube Kubernetes API server
    namespace: default  # The target namespace in Minikube

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true  # Add any other syncPolicy settings as needed
  # imagePullSecrets:
  # - name: dockerhub-secret    


